services:
  webui:
    build:
      context: ./webui
      dockerfile: ../Dockerfile
    working_dir: /app
    volumes:
      - ./webui:/app
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1

  auth:
    build:
      context: ./auth
      dockerfile: ../Dockerfile
    working_dir: /app
    volumes:
      - ./auth:/app
    environment:
      - PYTHONUNBUFFERED=1

  persistence:
    build:
      context: ./persistence
      dockerfile: ../Dockerfile
    working_dir: /app
    volumes:
      - ./persistence:/app
    environment:
      - PYTHONUNBUFFERED=1

  image:
    build:
      context: ./image
      dockerfile: ../Dockerfile
    working_dir: /app
    volumes:
      - ./image:/app
    environment:
      - PYTHONUNBUFFERED=1

  recommender:
    build:
      context: ./recommender
      dockerfile: ../Dockerfile
    working_dir: /app
    volumes:
      - ./recommender:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - persistence